#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

set -x

wmake all solvers/CLSVOF
wmake all solvers/CLSVOFte
#wmake all test
#wmake all utilities/preProcessing
#wmake all utilities/postProcessing
