#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

set -x

wmake all solvers/CLSVOF
wmake all solvers/CLSVOFte
wmake all solvers/CLSVOFcm
wmake all solvers/CLSFlow
wmake all solvers/CLSFlowsf
wmake all utilities/postProcessing/calcCLSErrors
wmake all utilities/postProcessing/calcVOFErrors
